- name: configuring backend
  hosts: backend
  become: yes
  tasks:
    - name: dnf module disable
      ansible.builtin.command: dnf module disable nodejs -y
       
    - name: dnf module enable
      ansible.builtin.command: dnf module enable nodejs:20 -y


    - name: Installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present  

    - name: Create expense user
      ansible.builtin.user:
        name: expense
        state: present    


         