- name: configuring backend server
  hosts: backend
  become: yes
  tasks:
    - name: disabling nodejs
      ansible.builtin.command: dnf module disable nodejs -y


    - name: disabling nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present  

    - name: Ensure the user "expense" exists
      ansible.builtin.user:
        name: expense               # The username you want to create
        state: present         
    