- name: configuring backend
  hosts: backend
  become: yes
  tasks:
    - name: dnf module disable
      ansible.builtin.command: dnf module disable nodejs -y
       
    - name: dnf module enable
      ansible.builtin.command: dnf module enable nodejs:20 -y


    - name: Installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present  

    - name: Create expense user
      ansible.builtin.user:
        name: expense
        state: present   


    - name: Ensure the directory /app exists
      ansible.builtin.file:
        path: /app
        state: directory   

    - name: Download the application code
      ansible.builtin.get_url:
        url: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip"
        dest: /tmp/backend.zip  
    
    - name: unarchieve
      ansible.builtin.unarchive:
        src: /tmp/backend.zip    # Path to the zip file
        dest:  /app            # Directory to extract to
        remote_src: yes  

         