- name: configuring backend server
  hosts: frontend
  become: yes
  tasks:
   - name: installling nginx
     ansible.builtin.package:
       name: nginx
       state: present

   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes    