- name: configuring backend server
  hosts: frontend
  become: yes
  tasks:
   - name: installling nginx
     ansible.builtin.package:
       name: nginx
       state: present

   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes 

   - name: ansible module to remove directory
     ansible.builtin.file:
      path: rm -rf /usr/share/nginx/html/*
      state: absent     

   - name: Download code (e.g., a tarball or zip file)
     ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip # URL to the code
        dest: /tmp/frontend.zip  #    
