
- name: Install MySQL Server on Debian/Ubuntu
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started 

    - name: ansible module to install pip
      ansible.builtin.pip:
        name: PyMySQL
        state: present       
    
    - name: Collect all info except settings and users by root
      community.mysql.mysql_info:
       login_user: root
       login_password: ExpenseApp@1
       login_host: mysql.daws83s.shop
      register: mysql_info
      ignore_errors: yes

    - name: ansible module to setup password
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1 
      when: mysql_info.failed is true

    - name: to import data
      community.mysql.mysql_user:
      
       login_user: root
       login_password: ExpenseApp@1
       login_host: mysql.daws83s.shop
       state: present
       name: all
       target: /app/schema/backend.sql

    - name: ansible module to start service
      ansible.builtin.service:
       name: backend    # Name of the service to be managed
       state: restarted      





