- name: Install MySQL Server
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL server (RHEL-based)
      ansible.builtin.package:
        name: mysql-server  # For RHEL/CentOS/Fedora
        state: present

    - name: Install MySQL server (Debian-based)
      ansible.builtin.package:
        name: mysql-server  # For Ubuntu/Debian systems
        state: present
      when: ansible_os_family == "Debian"
