- name: installing mysl server
  hosts: mysql
  become: yes
  tasks:
   - name: installing mysql-server
     ansible.builtin.package:
       name: mysql
       state: present
   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes




   
      