
- name: Install MySQL Server on Debian/Ubuntu
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started    
