---
- name: Installing MySQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Installing mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Starting service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        state: present


    - name: Get MySQL configuration variables
      community.mysql.mysql_info:
        login_user: root
        login_password: "ExpenseApp@1"
        login_host: mysql.daws83s.shop
        
      register: mysql_variables
      ignore_errors: yes     

    - name: seetup up password
      ansible.builtin.command:   mysql_secure_installation --set-root-pass ExpenseApp@1
        login_host: mysql.daws83s.shop
      when: mysql_variables.failed is true  

